### ISSUE TITLE
Can't program the ROM

### ISSUE THREAD

**Issue by wawachief** [omenmicro/bravo#1]
Hi

I'm having a hard time dealing with the ihex file of cmon : my ROM programmer does not recognize cmon.hex format as ihex and refuses to flash the rom. Do you have a .bin file ? 

Thank you for this project !

**Comment by maly** [comment]
Hello, fixed in commit a20b4558bcf2d71c37c7872a9d4d4b2929ce3215, look for sw/monitor/cmon.bin. The easiest way to convert HEX to BIN is with my online converter: https://www.asm80.com/tools/index.html#/hex2bin
